---
- name: Installation of NGINX on Docker
  hosts: docker
  become: true

  pre_tasks:
    - name: Install ansbile
      ansible.builtin.apt:
        name: ansible
        state: present
        update_cache: true

    - name: Install requirements
      ansible.builtin.command: ansible-galaxy collection install community.docker
      changed_when: false

  tasks:
    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: "true"
        cache_valid_time: "3600"

    - name: Install aptitude
      ansible.builtin.apt:
        name: aptitude
        state: present
        update_cache: true

    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present
        update_cache: true

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Pull nginx Docker image
      community.docker.docker_image:
        name: nginx
        source: pull

    - name: Create volume
      community.docker.docker_volume:
        name: docker-website
        driver: local

    - name: Run nginx Docker container
      community.docker.docker_container:
        name: docker-website
        image: nginx
        state: started
        ports:
          - 80:80
        volumes:
          - docker-website:/usr/share/nginx/html:ro
