---
- name: Digitalocean provision
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
    ssh_key: YOUR_SSH

  tasks:
    - name: Create Docker droplet
      community.digitalocean.digital_ocean_droplet:
        state: present
        oauth_token: "{{ oauth_token }}"
        name: docker
        private_networking: true
        size: s-1vcpu-512mb-10gb
        image: ubuntu-20-04-x64
        region: fra1
        ssh_keys: "{{ ssh_key }}"
        unique_name: true
      register: do

    - name: Get DigitalOcean API Token
      ansible.builtin.set_fact:
        do_token: "{{ oauth_token }}"

    - name: Get Droplet Information
      ansible.builtin.uri:
        url: https://api.digitalocean.com/v2/droplets
        method: GET
        headers:
          Authorization: Bearer {{ do_token }}
        return_content: true
      register: droplets

    - name: Extract Droplet IPs
      ansible.builtin.set_fact:
        droplet_ips: "{{ droplets.json.droplets | map(attribute='networks.v4') | flatten |
         selectattr('type', 'equalto', 'public') | map(attribute='ip_address') |
          list }}"

    - name: Add new host to Ansible inventory
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups:
          - docker
      loop: "{{ droplet_ips }}"
      when: droplet_ips is defined
